In [1]:
import requests
import pandas as pd

In [13]:
url = "https://api.opensea.io/api/v1/events"

querystring = {"only_opensea":"false","offset":"0","limit":"300"}

headers = {"Accept": "application/json"}

response = requests.request("GET", url, headers=headers, params=querystring)

output = response.json()

transactions = pd.DataFrame(data=output["asset_events"])

In [14]:
for column_name in transactions.columns:
    print(column_name)

approved_account
asset
asset_bundle
auction_type
bid_amount
collection_slug
contract_address
created_date
custom_event_name
dev_fee_payment_event
duration
ending_price
event_type
from_account
id
is_private
owner_account
payment_token
quantity
seller
starting_price
to_account
total_price
transaction
winner_account

In [15]:
transactions = transactions.drop(transactions[transactions["ending_price"].isnull() == 1].index)

In [16]:
transactions["ending_price"] = transactions["ending_price"].astype(int)

In [19]:
transactions[["created_date", "duration", "quantity", "starting_price", "ending_price"]].reset_index()

,index,created_date,duration,quantity,starting_price,ending_price
0,44,2021-10-01T15:05:45.600217,None,1,1000000000000,1000000000000
1,58,2021-10-01T15:05:45.500694,15724890,1,850000000000000000,850000000000000000
2,81,2021-10-01T15:05:45.340355,705,1,20000000000000000,20000000000000000
3,87,2021-10-01T15:05:45.293167,None,1,25000000000000000,25000000000000000
4,107,2021-10-01T15:05:45.211592,None,1,44000000000000000,44000000000000000
5,133,2021-10-01T15:05:44.981303,None,1,103000000000000000,103000000000000000
6,134,2021-10-01T15:05:44.986640,15724782,1,39000000000000000,39000000000000000
7,151,2021-10-01T15:05:44.897044,15721189,1,200000000000000000,200000000000000000
8,157,2021-10-01T15:05:44.865647,15724786,1,7000000000000000,7000000000000000
9,167,2021-10-01T15:05:44.818106,15724780,1,35000000000000000,35000000000000000
10,185,2021-10-01T15:05:44.765749,15724556,1,2700000000000000,2700000000000000
11,191,2021-10-01T15:05:44.757767,15724883,1,69000000000000000,69000000000000000
12,208,2021-10-01T15:05:44.735874,None,1,1600000000000000,1600000000000000
13,254,2021-10-01T15:05:44.471761,None,1,118000000000000000,118000000000000000
14,275,2021-10-01T15:05:44.282225,15724794,1,740000000000000,740000000000000